image: Visual Studio 2015

platform:
- x64

configuration:
  - Debug
  - Release

# http://www.appveyor.com/docs/installed-software
environment:
  global:
    BUILD_CONF: $(configuration)
  matrix:
  - QTDIR: C:\Qt\5.7\msvc2015
    PATH: C:\Qt\5.7\msvc2015\bin;%PATH%
    CMAKE_GENERATOR: "Visual Studio 14 2015"
  - QTDIR: C:\Qt\5.7\msvc2015_64
    PATH: C:\Qt\5.7\msvc2015_64\bin;%PATH%
    CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

build_script:
- git submodule update --init --recursive
- mkdir build
- cd build
- cmake -G "%CMAKE_GENERATOR%" ..
- cmake --build . --config %BUILD_CONF% -- /clp:ErrorsOnly
- ctest
