language: cpp
sudo: required
dist: trusty

os:
- linux
# - osx (temporari)

compiler:
# - clang (problems installing qt54base)
- gcc

branches:
  only:
  - master
  - develop

env:
- BUILD_TYPE=Debug
- BUILD_TYPE=Release

matrix:
 exclude:
 - os: osx
   compiler: gcc

before_install:
- chmod +x .travis/*/*.sh

install:
- .travis/${TRAVIS_OS_NAME}/install.sh

script:
- .travis/${TRAVIS_OS_NAME}/build_${BUILD_TYPE}.sh
- .travis/${TRAVIS_OS_NAME}/test_${BUILD_TYPE}.sh

addons:
  apt:
    sources:
    - sourceline: ppa:beineri/opt-qt542-trusty
    packages:
    - qt54base
    - xvfb
